### ISSUE TITLE
jeekim method get auto index more

### ISSUE THREAD

**Issue by jnkeniaem** [webservVer2-0/webServ#121]
## Description

auto index page에서 디렉/파일을 누르면 다운로드 되게

## Progress

- [x] 파일 다운로드
- [x] 디렉은 다운로드 x
- [x] . (현재 위치 나타내는거) 보여지는거 페이지에서 삭제
- [x] 현재 위치가 서버ROOT일때 .. 표시 안하고(상위 경로로 접근 못하게),
- [x] " 그치만 그것의 하위 경로면 .. 표시
- [x] 서버 autoindex on일 경우, 디렉경로 + 파일이름 > 처리 안하는걸루. get method에서 해당 조건문 삭제함
- [x] location autoindex on일 경우, /location < req에서 치환됨. 해당 위치 클릭했을때 표시되는 파일명은 
<img width="240" alt="Screen Shot 2023-03-27 at 4 34 27 PM" src="https://user-images.githubusercontent.com/80810728/227872140-d9cf2fdd-bb65-401f-941d-bb8669b8924c.png">
가 아니라 ./storage/static/auto_index/auto_index.html 이런식으로? > 그냥 원래대로 디렉 제외 파일명만 출력

- [x] 필요시 사용하는 모든 uri (변환한거, 기준 되는 경로 등) 정리하는 경로 구조체 필요. > 필요 없을걸로 보임
- [x] 이때 파일인지, 디렉인지 구분하는 플래그 저장(map 경로 전체를 합친 key, 파일명인 value 구조도 좋을듯). > set 2개로 디렉인지 파일인지 구분함. map 사용안함

**Comment by Paul2021-R** [comment]
통과했으니 클로즈~
