### ISSUE TITLE
hyunkkim-github_issue_template

### ISSUE THREAD

**Issue by khk811** [webservVer2-0/webServ#18]
이슈 작성의 원활함을 위해 develop 브랜치에 issue template을 등록하려고 합니다.
현재 이슈에 대한 description, to-do list 템플릿 및 기타 설명 작성 템플릿입니다.

**Comment by Paul2021-R** [comment]
진행 하시면 되요~ 하고 close 눌러주세용

**Comment by khk811** [comment]
이거 merge develop에 하면 되나요?
