### ISSUE TITLE
hyunkkim-request/response와 method 파트 간 구조체 정보 이용 방법 및 정보 교환 방법 의논

### ISSUE THREAD

**Issue by khk811** [webservVer2-0/webServ#20]
## Description

request, response 파트에서 어떻게 정보를 받아오고 어떻게 저장을 할지 의논하기 위해 이슈를 작성했습니다.
@Paul2021-R 님이 작성해주신 flowchart와 method pseudo code(15번 jeekim님 브랜치에 있습니다)에 모호한 내용이 있어서 질문 드립니다.

## Question
- [x] request에서 url을 어떤 형식으로 get method에 보내나요?
- [x] get method에서 open()한 파일을 method 측에서 char* entity (t_html내)에 넣어야 할까요?

## ETC
추후 궁금한 사항이 더 생긴다면 추가적으로 작성하겠습니다.

**Comment by Paul2021-R** [comment]
답변 
1 ) request 에서 uri는 실행 가능한 경로 형태로 보내줘야 합니다. 
예를 들어 현재 구조라면 
`./static/index.html `
이런 식이 되어야 합니다.(즉, 해당 파트에서 우선 간이 url을 받겠지만, 실행 가능한 구조로 바꿔줘야 한다는 것입니다. )

2 ) get method가 당연히 해당 부분에 채워주셔야 합니다. entity는 바이너리가 들어올 수도 있므로 길이까지 따로 넣어주는 겁니다.

**Comment by Paul2021-R** [comment]
더불어 인용하실 때는 

[  t_html response_msg_;
](https://github.com/webservVer2-0/webServ/blob/ce4e1360484c42e43365a894d7bdbb007000d661/include/datas.hpp#L132)

해당 지점 깃허브 line을 누르면 ... 하고 뜨는데 거기서 링크를 따서 인용해주시면 보다 확실히 소통 가능합니다.

**Comment by sangtale** [comment]
haryu님이 답변 주신 대로
uri는 method 파트에서 바로 사용할 수 있게 치환하는 것을 제가 구현합니다!(request message)

현재 branch에는 아직 이 부분이 구현이 안 돼있고,
어떻게 들어오는 지에 대해서 잘 몰라서 공부 중입니다... ^^)9

**Comment by khk811** [comment]
답변해 주신 내용을 바탕으로 생각한 GET method 구현 아이디어를 대략적으로 작성하겠습니다.
혹시 잘못된 내용이나 수정해야할 부분이 있다면 comment 달아주세요.

---
### GET method
1. https://github.com/webservVer2-0/webServ/blob/90ea932e1417bb4094aa33b8a09862dfccfa8d92/pseudo#L9
우선 파일을 open()합니다. 성공하면 status 변경 후 kevent에 등록하고 회귀합니다.
실패시 error 처리를 합니다.

2. https://github.com/webservVer2-0/webServ/blob/90ea932e1417bb4094aa33b8a09862dfccfa8d92/pseudo#L20
open 한 file descriptor에 read() 함수를 사용해 내용을 읽어옵니다.
읽은 내용은 buffer에 임시 저장한 후, vector에 옮겨 담습니다.
최종적으로 읽은 byte수와 (read()의 전체 반환값)과 vector의 size()값을 비교해서 올바르게 읽혔는지 확인하고, 전체 읽은 문자들과 총 길이를
https://github.com/webservVer2-0/webServ/blob/ce4e1360484c42e43365a894d7bdbb007000d661/include/datas.hpp#L132
이 구조체 안에 있는 entity와 entity_lenght에 저장합니다.

3. https://github.com/webservVer2-0/webServ/blob/90ea932e1417bb4094aa33b8a09862dfccfa8d92/pseudo#L25
읽기가 모두 끝난 fd를 close() 해줍니다.

**Comment by Paul2021-R** [comment]
https://github.com/webservVer2-0/webServ/blob/90ea932e1417bb4094aa33b8a09862dfccfa8d92/pseudo#L22
s_client_type 의 내부에 t_html response_msg_ 에 entity를 넣습니다.

**Comment by Paul2021-R** [comment]
https://github.com/webservVer2-0/webServ/blob/90ea932e1417bb4094aa33b8a09862dfccfa8d92/pseudo#L10
uri 경로는 반드시 requst에서 정리되어 오는 것으로, 유효성 검사까지 하시니 검사를 필요로 하지는 않습니다. 
그저 cache 타입에서 한번 확인하여, index.html이 존재하는 케이스인 경우 바로 해당 객체에서 데이터를 복제-client에 탑재-stage를 GET_FINISH로 점프하는 케이스를 만드시면 될 것으로 판단됩니다.

**Comment by khk811** [comment]
vector를 사용하지 않고 fseek(), ftell(), rewind()를 사용해서 파일 읽기 전 파일 크기를 계산하고 그 크기를 기반으로 한번에 fread()를 써서 읽어오는걸 실험해봤습니다. binary 파일과 html 파일 모두 똑같이 읽어오는것을 확인했습니다. (확인은 연 파일의 buffer를 파일로 한번 더 저장해서 원본 파일과 diff 명령어로 확인했습니다.) 그래서, 

GET method의 
https://github.com/webservVer2-0/webServ/blob/cd20c94c314231b81c0cf439abf9655e3eab0fae/pseudo#L22
이 부분에서 vector를 사용하지 않고, 한꺼번에 char*에 저장해서 넘기는 방식으로 구현방향을 변경해도 될것 같습니다.

**Comment by sangtale** [comment]
별개로 request_msg의 entity 동적할당을 해제 하는 시점은 어디가 될까요?

**Comment by khk811** [comment]
> 별개로 request_msg의 entity 동적할당을 해제 하는 시점은 어디가 될까요?

각 method 들의 모든 작업(읽고 쓰고 저장하는 작업 등등)이 끝나고 나서 return하기 전에 할당해제를 해주면 될 것 같습니다.
