### ISSUE TITLE
jinypark-access logging을 위한 client의 ip주소 수집

### ISSUE THREAD

**Issue by learnershigh** [webservVer2-0/webServ#23]
## Description
저희는 로컬 프로세스 간 통신만 하기 때문에 ip가 고정이지만
log에 단순 "127.0.0.1" or "localhost" 를 적어도 될지, ip를 받아와서 저장을 해야할지 모르겠습니다.

## Progress

- [ ] todo1
- [ ] todo2
- [ ] todo3

**Comment by Paul2021-R** [comment]
정하기 나름이려나...
