### ISSUE TITLE
bug-logger GetData()함수 내 container overflow오류

### ISSUE THREAD

**Issue by khk811** [webservVer2-0/webServ#56]
### Description

https://github.com/webservVer2-0/webServ/blob/fa99a43e61718e08b502aa0b231fc920cb68468f/src/logger/logger.cpp#L26

GetData() 함수에서 container overflow 오류가 발견되었습니다. 오류 내용은 아래와 같습니다.

---

=================================================================
==6435==ERROR: AddressSanitizer: container-overflow on address 0x602000000178 at pc 0x00010689b46e bp 0x7ff7b96a8090 sp 0x7ff7b96a8088
READ of size 8 at 0x602000000178 thread T0
    #0 0x10689b46d in s_logger_type::PushData() logger.cpp:26
    #1 0x106899763 in ServerRun(ServerConfig&) ServerInit.cpp:218
    #2 0x106859e18 in main main.cpp:23
    #3 0x114f0e51d in start+0x1cd (dyld:x86_64+0x551d)

0x602000000178 is located 8 bytes inside of 16-byte region [0x602000000170,0x602000000180)
allocated by thread T0 here:
    #0 0x106d6520d in wrap__Znwm+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5c20d)
    #1 0x10689a998 in s_logger_type::GetData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) logger.cpp:15
    #2 0x10687a4fb in s_client_type::SendLogs() datas.cpp:315
    #3 0x106899618 in ServerRun(ServerConfig&) ServerInit.cpp:188
    #4 0x106859e18 in main main.cpp:23
    #5 0x114f0e51d in start+0x1cd (dyld:x86_64+0x551d)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow logger.cpp:26 in s_logger_type::PushData()
Shadow bytes around the buggy address:
  0x1c03ffffffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03fffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c0400000000: fa fa fd fd fa fa 00 00 fa fa 00 00 fa fa 00 07
  0x1c0400000010: fa fa 00 04 fa fa fd fa fa fa 00 00 fa fa 00 fa
=>0x1c0400000020: fa fa fd fa fa fa 00 00 fa fa fd fa fa fa fc[fc]
  0x1c0400000030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6435==ABORTING
zsh: abort      ./webserv config/conf.d

---

**Comment by Paul2021-R** [comment]
여긴 아직 원인 규명이 불명인 것이네요. 안그래도 제가 알고 걍 방치해뒀던 거긴합니다 ㅋㅋ..
