### ISSUE TITLE
bug-io_wrapping_functions-for-eventdriven_server

### ISSUE THREAD

**Issue by Paul2021-R** [webservVer2-0/webServ#57]
## Description
kevent 기반으로 돌아가는 서버에서 read, write, recv, send 이 4가지의 함수들은 
단순 한번 호출로는 데이터가 완전히 들어오지 않을수 있다. 
따라서 이를 감싸는 wrapping 함수를 제작하여
데이터 무결성을 확보한 상태로 만드는게 핵심

**Comment by Paul2021-R** [comment]
kevent 기반의 서버에서 파일 입출력을 수행할 때에는 kevent 루프 안에서 읽기/쓰기를 해야 합니다. 이는 다음과 같은 이유 때문입니다.

kevent 루프는 이벤트가 발생할 때마다 이벤트를 처리하기 위한 적절한 작업(읽기/쓰기 등)을 수행합니다.
파일 입출력에서도 데이터가 도착하거나, 송신이 가능해질 때마다 이를 처리해야 합니다.
이를 위해서는 kevent 루프 안에서 파일 입출력을 수행하고, 이벤트가 발생할 때마다 입출력 작업을 수행해야 합니다.
따라서 kevent 루프 안에서 파일 입출력 함수를 호출하고, 이벤트가 발생할 때마다 이벤트를 처리하는 것이 필요합니다. 이를 통해 안정적이고 효율적인 파일 입출력을 수행할 수 있습니다.


chatGPT 내용

**Comment by Paul2021-R** [comment]
위에 내용 및 kevent 서버 구현시 kevent는 한개면 되는 줄 알았다... 
하지만 알고 보니 들어오는 자료들을 있을 경우 빠르게 읽고, 제대로 된건지 아닌지 기다려야 하는데, HTTP 메시지의 경우, 파일의 경우 들어오는 과정에서 생기는 걸수도 있고, 앤드가 언제인지 모른다. 따라서 kevent 회귀를 계속 하게 함으로써 읽은 만큼에서 판단하거나, 파일의 경우 파일 사이즈를 사전에 파악, 전체를 읽기를 시도 한 뒤 kevent에 들어가도록 처리 해야만 한다. 이를 간단하게 정리하면 다음과 같은 결론을 내린다는 것이다. 
1. 특정 읽기를 시도한다. 
2. 들어온 내용까지 중에서 read의 경우, 내부에 특성에 따라 끝을 표현하는 내용이 들어오지 않았거나, -1이지만, EAGAIN, EWOULBLOCK 인경우 다시 kevent로 회귀 해야 한다. 
3. HTTP메시지의 종료를 표현하는 CRLF 가 들어오거나, 청크의 경우 0/r/n/r/n 이 들어오거나, 파일의 경우 0(eof), 읽은 전체 사이즈가 file size에 부합하게 되었을 경우, 즉 다 읽었다느 증거가 들어올 때까지 일단 반복한다. 
4. 해당 조건에 부합하면? 작업을 마치고 다음 단계로 전달된다.

**Comment by jnkeniaem** [comment]
두번째 comment의 "kevent 기반의 서버에서 파일 입출력을 수행할 때에는 kevent 루프 안에서 읽기/쓰기를 해야 합니다."와 세번째 comment의 "전체를 읽기를 시도 한 뒤 kevent에 들어가도록 처리"가 충돌되는것같아서 그런데, 코드 예시 들어주실수있나요 ?

**Comment by jnkeniaem** [comment]
```
new_event_number = kevent();
for (;i < new_event_number;)
{
  if () {}
  else
  {
    switch ()
    {
      case WORK:
      {
        if (GET_START)
          WorkGet();
      }
      case CLIENT:
      {}
    }
  }
}

WorkGet()
{
  read();
}
```

지금은 위 구조인데, 아래와 같은 구조로 수정돼야한다는 건가요 ?

```
WorkGet()
{
  tmp = kevent();
  for (;i < tmp;)
  {
    read();
  }
}
```

**Comment by Paul2021-R** [comment]
그렇게도 가능하고, 아니면 read를 해서 완벽하게 들어오지 않았다는 조건이 들면 자시 메인 kevent에 이벤트를 등록하고 돌아갔다 다시 workGet으로 들어갈 수도 있습니다.

**Comment by Paul2021-R** [comment]
음 일단 구조적으로 말씀을 드리면 
kevent가 그렇게 들어가도 되구요.
아니면 구조를 틀어서, workget에 재진입하도록 만드는 방법도 있습니다. 
예를들면 ,
읽는다 - 파일 사이즈 함수로 파일 사이즈를 가져온다. - 리턴 값을 비교한다. 
1. 같다 -> 그대로 작업으로 들어간다.
2. -1 이지만 errno 가 EAGAIN이나 EW뭐시기로 기다려야 하는상황이다. -> return을 하되 현재 모든 설저은 그대로 둬서 다시 workget에 들어오게 만든다.
3. -1 이지만 위의 조건에 안맞는다 -> 에러로 판단하고 대응한다 
이렇게 나눠서 판단하면 될수도 있습니다. (어차피 kevent를 도는 건 맞으니까)
