### ISSUE TITLE
haryu-fix-Resetconnection-heap_delete

### ISSUE THREAD

**Issue by Paul2021-R** [webservVer2-0/webServ#97]
## Description

각 상황마다 entity의 delete가 필요한 경우가 있고, 아닌 경우가 있어 보인다. 이에 대응 해서 delete를 할 때와 아닌 경우를 확인해야 할 것으로 보여진다.

**Comment by learnershigh** [comment]
entity 포인터가 가리키는 곳은 t_http 클래스 속 vector<char> msg_의 내부이기 때문에 t_http가 없어지는 순간 알아서 소멸자가 호출이 됩니다. 그래서 entity자체는 해제할 필요가 없숩니다!!
