### ISSUE TITLE
sangtale-주석, 디버깅 용 메시지 출력 제거 + 리팩토링

### ISSUE THREAD

**Issue by sangtale** [webservVer2-0/webServ#98]
## Description
주석, 디버깅 용 메시지 출력 제거 + 리팩토링

## Progress

- [ ] todo1 필요없는 주석 제거
- [ ] todo2 디버깅 용 메시지 출력 제거
- [ ] todo3 다른 분들의 디버깅 용 메시지는 그대로 두겠습니다!

**Comment by Paul2021-R** [comment]
컨벤션 지켜서 올려주세요~
